toduck-App/toduck-backend

.gitignore
build.gradle
src/main/java/im/toduck/global/config/querydsl/QueryDslConfig.java

**1️⃣ QueryDSL 초기 설정**
- 프로젝트에 QueryDSL 초기 설정을 추가합니다. QueryDSL은 타입-세이프한 SQL 쿼리를 생성할 수 있게 해주는 프레임워크로, 복잡한 쿼리를 자바 코드로 작성할 수 있게 해줍니다.
1. `build.gradle` 파일에 QueryDSL 의존성 추가
2. QueryDSL Q 클래스 생성을 위한 Annotation Processor 설정
3. QueryDSL 설정을 위한 `JPAQueryFactory` 빈 등록
4. 샘플 엔티티에 대한 QueryDSL Q 클래스 생성 확인
<br/>
기타 내용
- @Nullable 어노테이션 처리를 위한 의존성 추가
https://github.com/TEAM-NANUM/server/tree/main/src/main/java/server/nanum/repository
위 레포지터리의 디렉터리 구조와 같이 QueryDSL을 통해 생성한 QClass를 사용하면 됩니다. 자세한 사용법은 사용이 필요한 경우에 별도로 공부하면 될 것 같습니다!

QueryDSL 초기 설정

---

sql/init.sql
src/main/java/im/toduck/domain/routine/common/mapper/RoutineMapper.java
src/main/java/im/toduck/domain/routine/domain/service/RoutineRecordService.java
src/main/java/im/toduck/domain/routine/domain/service/RoutineService.java
src/main/java/im/toduck/domain/routine/domain/usecase/RoutineUseCase.java
src/main/java/im/toduck/domain/routine/persistence/entity/Routine.java
src/main/java/im/toduck/domain/routine/persistence/entity/RoutineRecord.java
src/main/java/im/toduck/domain/routine/persistence/repository/RoutineRecordRepository.java
src/main/java/im/toduck/domain/routine/persistence/repository/RoutineRepository.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRecordRepositoryCustom.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRecordRepositoryCustomImpl.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRepositoryCustom.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRepositoryCustomImpl.java
src/main/java/im/toduck/domain/routine/presentation/api/RoutineApi.java
src/main/java/im/toduck/domain/routine/presentation/controller/RoutineController.java
src/main/java/im/toduck/domain/routine/presentation/dto/response/MyRoutineReadListResponse.java
src/main/java/im/toduck/global/helper/DaysOfWeekBitmask.java
src/test/java/im/toduck/RepositoryTest.java
src/test/java/im/toduck/builder/BuilderSupporter.java
src/test/java/im/toduck/builder/TestFixtureBuilder.java
src/test/java/im/toduck/domain/routine/domain/service/RoutineServiceTest.java
src/test/java/im/toduck/domain/routine/domain/usecase/RoutineUseCaseTest.java
src/test/java/im/toduck/domain/routine/persistence/repository/RoutineRecordRepositoryTest.java
src/test/java/im/toduck/domain/routine/persistence/repository/RoutineRepositoryTest.java
src/test/java/im/toduck/fixtures/RoutineFixtures.java
src/test/java/im/toduck/fixtures/RoutineRecordFixtures.java

**1️⃣ 루틴 목록 조회 API 개발**
자신의 루틴 목록을 날짜를 통해 조회하는 API를 개발했습니다.
가독성과 안정성 향상을 위해 QueryDSL을 사용하여 쿼리를 생성합니다. 
참고 링크: https://kyxxn.notion.site/672e4dbbd5a54bc7bb756cd6f5715b29?pvs=74
<br/>
**2️⃣ Repository 계층 테스트를 위한 Base 작성**
BuilderSupproter에 Redis 관련 레포지터리도 포함되어 있어, `@DataJpaTest`와 `@DataRedisTest`를 모두 포함시켰습니다.
<br/>
**3️⃣ 기타 기능 추가 및 수정**
- 테스트용 h2의 비트연산 대응을 위한 캐스팅 추가
참고: https://blog.hoony.me/2023/08/19/use-bitwise-operation-on-jpa
<br/>
`Routine` 이나 `RoutineRecord`와 같은 Entity의 CreatedAt이나 UpdatedAt이 비즈니스 로직이랑 연관되어 있어 테스트 시 해당 값들을 고정으로 가져가려고 했는데요(Fixture에서), Auditing 설정 때문에 해당 값들을 운영 코드의 수정 없이는 임의로 지정하지 못하는 상황입니다. 다양한 시도를 해보긴 했는데 혹시 좋은 아이디어 있으면 말해주세요!

루틴 목록 조회 API 개발

---

src/main/java/im/toduck/global/aop/log/LocalLogAspect.java
src/main/java/im/toduck/global/aop/log/ProdLogAspect.java
src/main/java/im/toduck/global/log/properties/InfoLogProperty.java

**1️⃣  로깅 null 에러 해결 **
- component에 적용되는 로깅이 매게인자와 반환값을 로그로 출력하는 과정에서 반환값이 null 이면 문자열 출력시 에러가 생겼습니다.
- 따라서 해당 부분을 Optional 대체 하였습니다.
<br/>

AOP 로 적용된 로그에서 null 에러 해결

---

src/main/java/im/toduck/domain/routine/common/mapper/RoutineMapper.java
src/main/java/im/toduck/domain/routine/domain/service/RoutineRecordService.java
src/main/java/im/toduck/domain/routine/domain/service/RoutineService.java
src/main/java/im/toduck/domain/routine/domain/usecase/RoutineUseCase.java
src/main/java/im/toduck/domain/routine/persistence/entity/Routine.java
src/main/java/im/toduck/domain/routine/persistence/repository/RoutineRecordRepository.java
src/main/java/im/toduck/domain/routine/persistence/repository/RoutineRepository.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRecordRepositoryCustom.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRecordRepositoryCustomImpl.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRepositoryCustom.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRepositoryCustomImpl.java
src/main/java/im/toduck/domain/routine/presentation/api/RoutineApi.java
src/main/java/im/toduck/domain/routine/presentation/controller/RoutineController.java
src/main/java/im/toduck/domain/routine/presentation/dto/response/RoutineDetailResponse.java
src/test/java/im/toduck/domain/routine/domain/usecase/RoutineUseCaseTest.java
src/test/java/im/toduck/domain/routine/persistence/repository/RoutineRecordRepositoryTest.java
src/test/java/im/toduck/domain/routine/persistence/repository/RoutineRepositoryTest.java
src/test/java/im/toduck/fixtures/RoutineFixtures.java
src/test/java/im/toduck/fixtures/RoutineRecordFixtures.java

**1️⃣ 루틴 삭제 기능 구현**
- Soft Delete 방식으로 구현 (deletedAt 필드 추가)
- 삭제 옵션 제공
- `keepRecords=true`: 기존 루틴 기록 유지 (단, 미래의 미완료 기록은 삭제)
- `keepRecords=false`: 모든 루틴 기록 삭제
<br/>
**2️⃣ 삭제된 루틴 접근성 개선**
- 삭제된 루틴도 조회 가능하도록 `getUserRoutineIncludingDeleted()` 메서드 추가
- 삭제 상태 여부를 응답에 포함 (`isInDeletedState` 필드 추가)
- 루틴의 삭제 시점 이전의 기록은 조회 가능하고, 이후의 기록은 조회 불가능하도록 구현
<br/>
**3️⃣ 삭제된 루틴 조회 로직 개선**
- 삭제된 루틴의 경우 삭제 시점 이후의 날짜로는 조회되지 않도록 수정
- Repository 계층에서 `routineNotDeletedOrDeletedAfterDate()` 추가하여 로직 구현
```java
// 날짜+시간이 삭제 시점보다 이전인 경우만 조회되도록 처리
private BooleanExpression routineNotDeletedOrDeletedAfterDate(
final TimePath<LocalTime> timePath, 
final LocalDate date 
) {
return qRoutine.deletedAt.isNull().or(
Expressions.booleanTemplate(
"cast(concat({0}, ' ', cast({1} as time)) as timestamp) < {2}",
date, …
```

루틴 삭제 API 개발

---

sql/init.sql
src/main/java/im/toduck/domain/routine/domain/service/RoutineService.java
src/main/java/im/toduck/domain/routine/persistence/repository/RoutineRepository.java
src/main/java/im/toduck/domain/social/common/mapper/SocialMapper.java
src/main/java/im/toduck/domain/social/domain/service/SocialBoardService.java
src/main/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCase.java
src/main/java/im/toduck/domain/social/persistence/entity/Social.java
src/main/java/im/toduck/domain/social/presentation/api/SocialBoardApi.java
src/main/java/im/toduck/domain/social/presentation/dto/request/SocialCreateRequest.java
src/main/java/im/toduck/domain/social/presentation/dto/request/SocialUpdateRequest.java
src/main/java/im/toduck/domain/social/presentation/dto/response/SocialDetailResponse.java
src/main/java/im/toduck/domain/social/presentation/dto/response/SocialResponse.java
src/main/java/im/toduck/global/exception/ExceptionCode.java
src/test/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCaseTest.java
src/test/java/im/toduck/fixtures/RoutineFixtures.java
src/test/java/im/toduck/fixtures/social/SocialFixtures.java

**1️⃣ 소셜 게시글과 루틴 연동**
```SQL
CREATE TABLE social
(
...
routine_id   BIGINT       NULL,
...
FOREIGN KEY (routine_id) REFERENCES routine (id)
);
```
- 소셜 게시글 생성, 수정, 조회 시 루틴 정보를 연동하도록 기능을 구현
<br/>
**2️⃣ 데이터베이스 초기화 순서 수정**
**변경 전:**
```SQL
INSERT INTO social (...) VALUES (...);
INSERT INTO routine (...) VALUES (...);
```
**변경 후:**
```SQL
INSERT INTO routine (...) VALUES (...);
INSERT INTO social (...) VALUES (...);
```
<br/>
- 루틴 연동 관련 코드 개선이 필요한 부분이 있는지 확인 부탁드립니다.
- 특히, 게시글 수정 시 `routineId`가 `null`인 경우 변경 없음 `0`인 경우 제거, `유효한 Id` 인 경우 루틴 수정 처리가 올바르게 구현되었는지 확인 부탁드립니다.

소셜 게시글과 루틴 연동

---

build.gradle
src/main/java/im/toduck/global/config/s3/S3Config.java
src/main/java/im/toduck/global/exception/ExceptionCode.java
src/main/java/im/toduck/infra/s3/common/S3Mapper.java
src/main/java/im/toduck/infra/s3/domain/service/S3Service.java
src/main/java/im/toduck/infra/s3/domain/usecase/S3UseCase.java
src/main/java/im/toduck/infra/s3/presentation/api/S3ControllerApi.java
src/main/java/im/toduck/infra/s3/presentation/controller/S3Controller.java
src/main/java/im/toduck/infra/s3/presentation/dto/ImageExtension.java
src/main/java/im/toduck/infra/s3/presentation/dto/request/FileNameDto.java
src/main/java/im/toduck/infra/s3/presentation/dto/request/PreSignedUrlRequest.java
src/main/java/im/toduck/infra/s3/presentation/dto/response/FileUrlDto.java
src/main/java/im/toduck/infra/s3/presentation/dto/response/PreSignedUrlResponse.java
src/main/resources/application.yml
src/test/java/im/toduck/infra/s3/domain/usecase/S3UseCaseTest.java

**1️⃣ S3 Presigned Url 발급 api 개발**
**Request**
- 한 번에 여러 파일을 처리 가능
```JSON
{
"fileNameDtos": [
{
"fileName": "example1.png"
},
{
"fileName": "example2.jpg"
}
]
}
```
**Response**
```JSON
{
"fileUrlsDtos": [
{
"presignedUrl": "https://${BUCKET_NAME}.s3.ap-northeast-2.amazonaws.com/users/1/2025/1/15/...",
"fileUrl": "https://cdn.toduck.app/users/${USER_ID}/${YEAR}/${MONTH}/${DAY}/${UUID}_example1.png"
},
{
"presignedUrl": "https://${BUCKET_NAME}.s3.ap-northeast-2.amazonaws.com/users/1/2025/1/15/...",
"fileUrl": "https://cdn.toduck.app/users/${USER_ID}/${YEAR}/${MONTH}/${DAY}/${UUID}_example2.jpg"
}
]
}
```
<br/>
**2️⃣ CloudFront CDN 도입**
**CloudFront 배포 설정**
- CloudFront를 S3 버킷에 연결
- `cdn.toduck.app` 을 도메인 이름으로 사용하도록 설정 (Route 53 및 SSL 인증서 설정 포함).
**CDN 적용 결과**
- Before: …

S3 Prsigned Url 발급 api 개발

---

src/main/java/im/toduck/domain/schedule/common/mapper/ScheduleMapper.java
src/main/java/im/toduck/domain/schedule/common/mapper/ScheduleRecordMapper.java
src/main/java/im/toduck/domain/schedule/domain/service/ScheduleRecordService.java
src/main/java/im/toduck/domain/schedule/domain/service/ScheduleService.java
src/main/java/im/toduck/domain/schedule/domain/usecase/ScheduleUseCase.java
src/main/java/im/toduck/domain/schedule/persistence/entity/Schedule.java
src/main/java/im/toduck/domain/schedule/persistence/entity/ScheduleRecord.java
src/main/java/im/toduck/domain/schedule/persistence/repository/querydsl/ScheduleRecordRepositoryCustom.java
src/main/java/im/toduck/domain/schedule/persistence/repository/querydsl/ScheduleRecordRepositoryCustomImpl.java
src/main/java/im/toduck/domain/schedule/persistence/vo/ScheduleDate.java
src/main/java/im/toduck/domain/schedule/presentation/api/ScheduleApi.java
src/main/java/im/toduck/domain/schedule/presentation/controller/ScheduleController.java
src/main/java/im/toduck/domain/schedule/presentation/dto/request/ScheduleCompleteRequest.java
src/main/java/im/toduck/domain/schedule/presentation/dto/request/ScheduleDeleteRequest.java
src/main/java/im/toduck/domain/schedule/presentation/dto/response/ScheduleHeadResponse.java
src/main/java/im/toduck/domain/schedule/presentation/dto/response/ScheduleInfoResponse.java
src/main/java/im/toduck/global/exception/ExceptionCode.java
src/test/java/im/toduck/domain/schedule/domain/usecase/ScheduleUseCaseTest.java
src/test/java/im/toduck/domain/schedule/persistence/repository/ScheduleRecordRepositoryTest.java

**1️⃣ 일정 완료 API 개발**
> 일정 완료 여부를 변경하는 요청일 시 일정 기록(Schedule_record)를 생성하도록 구현했습니다.
> 복잡한 로직은 없으니 테스트 케이스만 보시고 이상한 점 말씀해주세요
<br/>
**2️⃣ 일정 삭제 API 개발**
> 일정 삭제 API 는 다소 복잡합니다. 
> 일정 기록 삭제에 전체 삭제는 존재하지 않고 특정 날짜 이후 삭제와 하루 삭제만 존재합니다.
> ScheduleRecord의 deletedAt을 사용했습니다. soft delete를 적용하지 않고 해당 값의 null 여부로 삭제되었는지 판단합니다.
> 특정 날짜 이후 삭제는 완료 기록들은 남겨두고 미 완료 기록들만 삭제합니다.
기간 x 반복 x
- 바로 삭제 ( 완료 여부 상관 없이 삭제 , 하루 삭제만 존재)
기간 x  반복 O
- 하루 삭제
ScheduleRecord 에 deleteAt필드를 사용할 예정
- 해당 날짜에 대한 일정 기록이 있을시
- deleteAt 를 null
- 해당 날짜에 대한 일정 기록이 없을시
- deleteAt 초기화
- 특정 날짜 이후 삭제
- 기간 x 반복 O → 기간 O 반복 O 로 수정할 것임
- endDate날짜를 특정 날짜로 수정
- 특정 날짜 이후 일정 기록들도 삭제
- ***단,완료된 일정들은 하루짜리 반복 x 일정으로 수정***
기간 o 반복 O,X
- 하루 삭제
- 위와 동일
- 특정 날짜 이후 삭제
- 위와 동일
<br/>
- 코드와 로직이 다소 복잡한데 테스트 코드를 잘 작성했는지 피드백 부탁드립니다

일정 삭제 API 개발

---

src/main/java/im/toduck/domain/auth/domain/service/GeneralAuthService.java
src/main/java/im/toduck/domain/auth/domain/usecase/AuthUseCase.java
src/main/java/im/toduck/domain/auth/presentation/api/AuthControllerApi.java
src/main/java/im/toduck/domain/auth/presentation/dto/request/LoginRequest.java
src/main/java/im/toduck/domain/auth/presentation/dto/request/SignUpRequest.java
src/main/java/im/toduck/domain/user/domain/service/UserService.java
src/main/java/im/toduck/global/exception/ExceptionCode.java

**1️⃣ 일반 로그인 식별자 수정**
- 로그인 식별자로 `전화번호` 를 사용하던 것에서 `로그인 ID` 를 사용하는 것으로 수정
```JSON
{
"loginId": "toduck",
"password": "password123"
}
```
<br/>
**2️⃣ api 문서에 있는 비밀번호 예시 정규식에 맞게 수정**
- 변경 전
```JAVA
@Schema(description = "사용자 비밀번호", example = "password123")
```
- 변경 후
```JAVA
@Schema(description = "사용자 비밀번호", example = "Password2025@")
```
- 궁금한 점이 있다면 댓글 남겨주세요!

일반 로그인 식별자 수정

---

src/main/java/im/toduck/domain/schedule/common/mapper/ScheduleMapper.java
src/main/java/im/toduck/domain/schedule/common/mapper/ScheduleRecordMapper.java
src/main/java/im/toduck/domain/schedule/domain/service/ScheduleModifyService.java
src/main/java/im/toduck/domain/schedule/domain/service/ScheduleReadService.java
src/main/java/im/toduck/domain/schedule/domain/service/ScheduleRecordService.java
src/main/java/im/toduck/domain/schedule/domain/service/ScheduleService.java
src/main/java/im/toduck/domain/schedule/domain/usecase/ScheduleUseCase.java
src/main/java/im/toduck/domain/schedule/persistence/entity/Schedule.java
src/main/java/im/toduck/domain/schedule/persistence/repository/querydsl/ScheduleRecordRepositoryCustom.java
src/main/java/im/toduck/domain/schedule/persistence/repository/querydsl/ScheduleRecordRepositoryCustomImpl.java
src/main/java/im/toduck/domain/schedule/presentation/api/ScheduleApi.java
src/main/java/im/toduck/domain/schedule/presentation/controller/ScheduleController.java
src/main/java/im/toduck/domain/schedule/presentation/dto/request/ScheduleModifyRequest.java
src/main/java/im/toduck/domain/schedule/presentation/dto/response/ScheduleIdResponse.java
src/main/java/im/toduck/global/exception/ExceptionCode.java
src/test/java/im/toduck/domain/schedule/domain/usecase/ScheduleUseCaseTest.java
src/test/java/im/toduck/domain/schedule/persistence/repository/ScheduleRecordRepositoryTest.java

> 일정 수정 API 는 다소 복잡합니다
> 일정 수정 로직은 전체 수정은 없습니다
> 하루 일정 수정과 특정날짜(queryDate) 이후 일정 일괄 수정만 존재합니다
- 하루 , 반복 x 일정 경우에는 schedule 레코드를 수정합니다.
- 다른 경우의 수의 일정들은 해당 날짜 일정 기록을 soft delete하여 삭제 마킹을 합니다
- 기존 일정의 endDate 를 queryDate 하루 전으로 수정합니다 ( 삭제  api 로직과 동일)
- queryDate로 시작하는 수정 일정을 새로 생성 합니다.
- 기존 일정의 queryDate 이후의 일정 기록중 완료 기록은 각각 하루짜리 반복x 인 일정으로 남겨둡니다.
- 기존 일정의 queryDate 이후의 일정 기록중  미완료 기록은 삭제됩니다.
- 특정 날짜를 선택하고 기간 일정으로 수정을 하고 이후 날짜 일괄 수정을 해서 발생하는 경우의 수
-  해당 경우의 수는 논리적으로 존재할 수 없으므로 예외처리 하였습니다.
<br>
- 하루 짜리 반복 x 일정을 특정 날짜 이후 수정 할 수 있나? 
- 해당 로직은 논리적으로 존재할 수 없으므로 예외처리 하였습니다.

일정 수정 API 개발

---

src/main/java/im/toduck/domain/social/domain/service/SocialBoardService.java
src/test/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCaseTest.java

**1️⃣ 소셜 게시글 이미지 추가 로직 수정**
-  imageUrls가 null 또는 빈 값인 경우, 바로 리턴하도록 수정하여 `NullPointerException` 해결 
- 질문 있으시면 댓글 남겨주세요!

소셜 게시글 이미지가 null/빈 값 에러 해결

---

sql/init.sql
src/main/java/im/toduck/domain/social/common/mapper/CommentImageFileMapper.java
src/main/java/im/toduck/domain/social/common/mapper/CommentMapper.java
src/main/java/im/toduck/domain/social/domain/service/SocialBoardService.java
src/main/java/im/toduck/domain/social/domain/service/SocialInteractionService.java
src/main/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCase.java
src/main/java/im/toduck/domain/social/domain/usecase/SocialInteractionUseCase.java
src/main/java/im/toduck/domain/social/persistence/entity/CommentImageFile.java
src/main/java/im/toduck/domain/social/persistence/repository/CommentImageFileRepository.java
src/main/java/im/toduck/domain/social/presentation/dto/request/CommentCreateRequest.java
src/main/java/im/toduck/domain/social/presentation/dto/response/CommentDto.java
src/test/java/im/toduck/domain/social/domain/usecase/SocialInteractionUseCaseTest.java

**1️⃣ comment_image_file 테이블 추가**
```SQL
CREATE TABLE comment_image_file
(
id         BIGINT PRIMARY KEY auto_increment,
comment_id BIGINT        NOT NULL,
url        VARCHAR(1024) NOT NULL,
...
);
```
<br/>
**2️⃣ 요청/응답에서 이미지 관련 필드 추가**
```JAVA
public record CommentCreateRequest(
...
@Nullable
@Schema(description = "이미지 URL", nullable = true, example = "https://cdn.toduck.app/example.jpg")
String imageUrl
) {
}
```
```JAVA
public record CommentDto(
...
@Schema(description = "사진 포함 여부", example = "true")
Boolean hasImage,
@Schema(description = "사진 주소", example = "https://cdn.toduck.app/example.jpg")
String imageUrl,
...
) {
}
```
<br/>
**3️⃣ 게시글/댓글 삭제 시 댓글 이미지 파일 삭제**
- 게시글 삭제 시 (**soft delete**)
- 댓글 삭제 시 (**hard delete**)
<br/>
- 궁금한 점 있으시면 댓글 달아주세요!

댓글 이미지 첨부 기능 추가

---

src/main/java/im/toduck/domain/auth/domain/usecase/GeneralSignUpUseCase.java
src/main/java/im/toduck/domain/schedule/presentation/dto/request/ScheduleCreateRequest.java
src/main/java/im/toduck/domain/user/domain/service/UserService.java
src/main/java/im/toduck/domain/user/domain/usecase/UserAuthUseCase.java
src/main/java/im/toduck/domain/user/persistence/entity/User.java
src/main/java/im/toduck/domain/user/presentation/api/UserAuthApi.java
src/main/java/im/toduck/domain/user/presentation/controller/UserAuthController.java
src/main/java/im/toduck/domain/user/presentation/dto/request/ChangePasswordRequest.java
src/main/java/im/toduck/domain/user/presentation/dto/request/VerifyLoginIdPhoneNumberRequest.java
src/main/java/im/toduck/domain/user/presentation/dto/response/LoginIdResponse.java
src/main/java/im/toduck/global/config/security/SecurityConfig.java
src/main/java/im/toduck/global/exception/ExceptionCode.java
src/main/java/im/toduck/infra/redis/phonenumber/PhoneNumberService.java
src/main/java/im/toduck/infra/redis/phonenumber/PhoneNumberServiceImpl.java

> 해당 안내는 지워주세요.  
> 이번 PR에서 작업한 내용을 간략히 설명해주세요.  
> 스크린샷을 적극적으로 활용해 주세요.
**1️⃣ 기존 휴대폰 인증 후 회원가입 성공하면 전화번호 인증 정보 강제 삭제하도록 수정 **
- 전화번호 인증 정보가 ttl 로 시간이 지나면 삭제되도록 했지만, id 찾기 와 비밀번호 변경 시 필요한 전화번호 인증에 재사용 될것을 염두하여 수정했습니다.
**2️⃣ 유저 id 찾기**
> 기존 인증번호 발송 api를 재사용 안한 이유는 기존 api 는 유저가 있는지 검증 후 있으면 에러를 반환하므로 해당 인증 번호 발송 api 를 재사용하기에는 비즈니스 니즈가 다르다고 판단하에 새로 api 를 구현했습니다.
유저 id 찾기 과정
1. 전화번호 인증 번호 발송
2. 전화번호 인증 번호 검증
3. 검증된 전화번호라면 유저 id 찾기 성공
<br/>
**3️⃣ 비밀번호 변경**
비밀번호 변경 과정 
1. 전화번호 인증 번호 발송
2. 전화번호 인증 번호 검증
3. 검증 된 전화번호와 유저 id 를 보내서 비밀번호 변경이 가능한지 확인 (api로 제공)
4. 유저 id 와 검증된 전화번호 그리고 비밀번호를 보내면 해당 비밀번호로 인코딩 후 유저의 비밀번호를 변경함
<br/>

자체 회원가입 유저 id 찾기 및 비밀번호 변경 API 개발

---

src/main/java/im/toduck/domain/diary/common/mapper/DiaryImageFileMapper.java
src/main/java/im/toduck/domain/diary/common/mapper/DiaryMapper.java
src/main/java/im/toduck/domain/diary/domain/service/DiaryService.java
src/main/java/im/toduck/domain/diary/domain/usecase/DiaryUseCase.java
src/main/java/im/toduck/domain/diary/persistence/entity/Diary.java
src/main/java/im/toduck/domain/diary/persistence/entity/DiaryImage.java
src/main/java/im/toduck/domain/diary/persistence/repository/DiaryImageRepository.java
src/main/java/im/toduck/domain/diary/persistence/repository/DiaryRepository.java
src/main/java/im/toduck/domain/diary/presentation/api/DiaryApi.java
src/main/java/im/toduck/domain/diary/presentation/controller/DiaryController.java
src/main/java/im/toduck/domain/diary/presentation/dto/request/DiaryCreateRequest.java
src/main/java/im/toduck/domain/diary/presentation/dto/request/DiaryUpdateRequest.java
src/main/java/im/toduck/domain/diary/presentation/dto/response/DiaryCreateResponse.java
src/main/java/im/toduck/domain/diary/presentation/dto/response/DiaryImageDto.java
src/main/java/im/toduck/domain/diary/presentation/dto/response/DiaryResponse.java
src/main/java/im/toduck/global/exception/ExceptionCode.java

> Diary 삭제, 수정, 특정 연월 일기 조회 API를 작성했습니다.
**1️⃣ 작업내용1**
- 수정시에 `date` 값은 변하면 안되기 때문에 제외했고 `emotion` 값은 변경할 수 있으나 `NotNull`이기 때문에 예외처리에 신경썼습니다.  다른 변수들은 `null`이 아닌 경우 수정하도록 했지만 `emotion`은 `isChangeEmotion`이 `true`인 경우에만 수정하도록 했습니다. `isChangeEmotion`이 `false`인 경우에도 `emotion` 값에는 `null`이 들어가면 안될 것 같아 그에 대한 예외처리 코드를 DiaryService에 작성했습니다. 자세한 내용은 DiaryApi에 작성했습니다.
<br/>
**2️⃣ 작업내용2**
- 특정 연월 일기 조회는 year(yyyy)와 month(MM)를 param에 전달하면 해당 달에 작성된 일기들의 정보를 가져옵니다.
아래 화면에서 사용될 것을 생각하여 만들었습니다.
<br/>
> 일기에는 이미지가 최대 2개까지 들어가는데 지금 코드로는 사진을 2개 올리고 하나만 수정을 할 수 있는지 모르겠습니다.
> 사진은 최대 2개까지 올릴 수 있는데 DiaryUpdateRequest에 `diaryImageUrls`에 `@Size`에 `max`값을 2로 주면 이것만으로 예외처리가 되는지 궁금합니다.
> 일기를 조회할 때 Mapper를 사용하지 않는 방식으로 했는데 이렇게 해도 되는지 궁금합니다.
> 일기를 저장할 때 시간 순서에 따라 차례대로 저장이 될텐데 그럼 조회할 때 따로 정렬을 하지 않아도 정렬된 순서로 값을 가져오는지 …

diary crud API

---

src/main/java/im/toduck/domain/diary/common/mapper/DiaryMapper.java
src/main/java/im/toduck/domain/diary/domain/service/DiaryService.java
src/main/java/im/toduck/domain/diary/domain/usecase/DiaryUseCase.java
src/main/java/im/toduck/domain/diary/persistence/entity/Diary.java
src/main/java/im/toduck/domain/diary/persistence/entity/DiaryImage.java
src/main/java/im/toduck/domain/diary/persistence/repository/DiaryRepository.java
src/main/java/im/toduck/domain/diary/presentation/api/DiaryApi.java
src/main/java/im/toduck/domain/diary/presentation/controller/DiaryController.java
src/main/java/im/toduck/domain/diary/presentation/dto/request/DiaryCreateRequest.java
src/main/java/im/toduck/domain/diary/presentation/dto/request/DiaryUpdateRequest.java
src/main/java/im/toduck/domain/diary/presentation/dto/response/DiaryResponse.java
src/main/java/im/toduck/global/exception/ExceptionCode.java

> 로컬 서버에서 테스트 했을 때 발생한 오류들을 수정했습니다.
**1️⃣ 작업내용1**
- 일기 목록을 조회할 때 일기 번호도 함께 전달하도록 수정했습니다.
- JSON 데이터를 LocalDate 타입으로 변환할 수 있도록 `@JsonDeserialize(using = LocalDateDeserializer.class)` 어노테이션을 추가했습니다.
- 일기는 하루에 하나만 존재하므로 이미 일기가 작성된 날에 다시 create를 요청할 경우 오류를 추가했습니다.
- 여러 오타들을 수정했습니다.
<br/>

Diary CRUD API 오류 수정

---

src/main/java/im/toduck/domain/diary/common/mapper/DiaryMapper.java
src/main/java/im/toduck/domain/diary/domain/service/DiaryService.java
src/main/java/im/toduck/domain/diary/domain/usecase/DiaryUseCase.java
src/main/java/im/toduck/domain/diary/persistence/repository/DiaryRepository.java
src/main/java/im/toduck/domain/diary/presentation/api/DiaryApi.java
src/main/java/im/toduck/domain/diary/presentation/controller/DiaryController.java
src/main/java/im/toduck/domain/diary/presentation/dto/response/MonthDiaryResponse.java

> 일기 화면 통계 부분에 사용될 API 입니다.
**1️⃣ 작업내용1**
- 연월을 입력하면 해당 월과 전월의 일기의 개수 차이를 알려줍니다.
> 매핑 이름 더 나은 게 있을까요?

특정 연월 일기 개수 (전월 대비) 조회 API

---

src/main/java/im/toduck/domain/routine/common/mapper/RoutineMapper.java
src/main/java/im/toduck/domain/routine/domain/service/RoutineService.java
src/main/java/im/toduck/domain/routine/persistence/repository/RoutineRepository.java
src/main/java/im/toduck/domain/social/common/mapper/SocialProfileMapper.java
src/main/java/im/toduck/domain/social/domain/service/SocialBoardService.java
src/main/java/im/toduck/domain/social/domain/service/SocialInteractionService.java
src/main/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCase.java
src/main/java/im/toduck/domain/social/domain/usecase/SocialProfileUseCase.java
src/main/java/im/toduck/domain/social/persistence/repository/CommentRepository.java
src/main/java/im/toduck/domain/social/persistence/repository/SocialRepository.java
src/main/java/im/toduck/domain/social/persistence/repository/querydsl/SocialRepositoryCustom.java
src/main/java/im/toduck/domain/social/persistence/repository/querydsl/SocialRepositoryCustomImpl.java
src/main/java/im/toduck/domain/social/presentation/api/SocialProfileApi.java
src/main/java/im/toduck/domain/social/presentation/controller/SocialProfileController.java
src/main/java/im/toduck/domain/social/presentation/dto/response/SocialProfileResponse.java
src/main/java/im/toduck/domain/social/presentation/dto/response/UserProfileRoutineListResponse.java
src/main/java/im/toduck/domain/user/domain/service/FollowService.java
src/main/java/im/toduck/domain/user/persistence/repository/FollowRepository.java
src/test/java/im/toduck/builder/BuilderSupporter.java
src/test/java/im/toduck/builder/TestFixtureBuilder.java
src/test/java/im/toduck/domain/social/domain/usecase/SocialProfileUseCaseTest.java
src/test/java/im/toduck/fixtures/RoutineFixtures.java

> 해당 PR의 api는 총 3개입니다!
> 게시글 목록 조회, 게시글 단건 조회, 게시글 검색 시 N+1 문제가 발생하는 것을 인지하고 있으며, 추후 PR에서 수정하겠습니다!
**1️⃣ 소셜 프로필 - 유저 정보 조회**
- 배지는 1차 출시 계획에서 제외됨
<br/>
**2️⃣  소셜 프로필 - 유저 공개 루틴 목록 조회**
- 루틴 공유수는 다음 PR에서 추가 후 적용할 예정
<br/>
**3️⃣ 소셜 프로필 - 유저 작성 게시글 조회**
<br/>
- 궁금한 점 있으면 댓글 남겨주세요!

소셜 프로필 조회 API 개발

---

src/main/java/im/toduck/domain/diary/common/mapper/DiaryMapper.java
src/main/java/im/toduck/domain/diary/domain/usecase/DiaryUseCase.java
src/main/java/im/toduck/domain/diary/presentation/api/DiaryApi.java
src/main/java/im/toduck/domain/diary/presentation/controller/DiaryController.java
src/main/java/im/toduck/domain/diary/presentation/dto/response/DiaryListResponse.java

> Diary Response를 List에 담아서 반환하도록 수정했습니다.
**1️⃣ 작업내용1**
- 설명1
<br/>
**2️⃣ 작업내용2**
- 설명1
<br/>
**3️⃣ 작업내용3**
- 설명1
<br/>

월별 일기 조회 API 응답 구조 변경

---

src/main/java/im/toduck/domain/social/common/mapper/SocialMapper.java
src/main/java/im/toduck/domain/social/domain/service/SocialBoardService.java
src/main/java/im/toduck/domain/social/domain/service/SocialCategoryService.java
src/main/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCase.java
src/main/java/im/toduck/domain/social/domain/usecase/SocialProfileUseCase.java
src/main/java/im/toduck/domain/social/persistence/repository/querydsl/SocialRepositoryCustom.java
src/main/java/im/toduck/domain/social/persistence/repository/querydsl/SocialRepositoryCustomImpl.java
src/main/java/im/toduck/domain/social/presentation/api/SocialBoardApi.java
src/main/java/im/toduck/domain/social/presentation/controller/SocialBoardController.java
src/main/java/im/toduck/domain/social/presentation/dto/response/SocialResponse.java
src/test/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCaseTest.java

**1️⃣ 게시글 검색 시 카테고리 필터 기능 추가**
- 사용자가 게시글을 검색할 때 특정 카테고리를 기준으로 필터링할 수 있는 기능 추가
<br/>
**2️⃣ 카테고리 필터링 조건 변경 (AND 조건 적용)**
- 여러 카테고리를 동시에 필터링할 경우, 선택된 모든 카테고리를 만족하는 게시글만 조회되도록 수정
* (기존 문제: `SLEEP`, `MEMORY` 필터 적용 시, 둘 중 하나의 카테고리만 포함된 게시글도 함께 조회되는 문제)
- 궁금한 점이 있으면 댓글 남겨주세요!

게시글 검색 시 카테고리 필터 추가

---

sql/init.sql
src/main/java/im/toduck/domain/routine/common/mapper/RoutineMapper.java
src/main/java/im/toduck/domain/routine/domain/service/RoutineService.java
src/main/java/im/toduck/domain/routine/persistence/entity/Routine.java
src/main/java/im/toduck/domain/routine/persistence/repository/RoutineRepository.java
src/main/java/im/toduck/domain/social/common/mapper/SocialProfileMapper.java
src/main/java/im/toduck/domain/social/domain/usecase/SocialProfileUseCase.java
src/main/java/im/toduck/domain/social/presentation/api/SocialProfileApi.java
src/main/java/im/toduck/domain/social/presentation/controller/SocialProfileController.java
src/main/java/im/toduck/domain/social/presentation/dto/request/ReportCreateRequest.java
src/main/java/im/toduck/domain/social/presentation/dto/response/SocialProfileResponse.java
src/main/java/im/toduck/domain/social/presentation/dto/response/UserProfileRoutineListResponse.java
src/test/java/im/toduck/domain/social/domain/usecase/SocialProfileUseCaseTest.java

**1️⃣ 루틴 공유 횟수 필드 추가**
```SQL
CREATE TABLE routine
(
...
shared_count     INT UNSIGNED       DEFAULT 0                        NOT NULL,
...
);
```
<br/>
**2️⃣ 루틴 공유 API 개발**
- 사진에서 보여지는 버튼을 통해 공개 되어진 루틴을 저장 
- 사진에서 보여지는 것처럼 내용, 시간, 반복, 공개 여부, 메모 등은 모두 수정 가능하므로 원본 루틴의 값을 사용해 새로운 루틴을 만들지 않고, `RoutineCreateRequest` 로 값을 받아 생성한 후 원본 루틴의 공유 횟수만 증가하도록 했습니다!
<br/>
**3️⃣ 소셜 프로필의 공개 루틴 조회시 루틴 공유 수 필드 추가**
```JAVA
public record UserProfileRoutineListResponse(
... 
@Schema(description = "루틴 공유 수 총합", example = "1304")
int totalSharedCount
) {
public record UserProfileRoutineResponse(
... 
@Schema(description = "루틴 공유 수", example = "455")
int sharedCount,
... 
) {
}
}
```
- 궁금한 점이 있다면 댓글 남겨주세요!
- 게시글 신고 dto 검증 필드 관련, 소셜 프로필 팔로우 여부 살짝 끼워넣기 했습니다..ㅎ

루틴 공유 api 개발

---

src/main/java/im/toduck/domain/concentration/common/mapper/ConcentrationMapper.java
src/main/java/im/toduck/domain/concentration/domain/service/ConcentrationService.java
src/main/java/im/toduck/domain/concentration/domain/usecase/ConcentrationUseCase.java
src/main/java/im/toduck/domain/concentration/persistence/repository/ConcentrationRepository.java
src/main/java/im/toduck/domain/concentration/persistence/repository/ConcentrationRepositoryCustom.java
src/main/java/im/toduck/domain/concentration/persistence/repository/ConcentrationRepositoryCustomImpl.java
src/main/java/im/toduck/domain/concentration/persistence/repository/ConcentrationRepositoryImpl.java
src/main/java/im/toduck/domain/concentration/presentation/api/ConcentrationApi.java
src/main/java/im/toduck/domain/concentration/presentation/controller/ConcentrationController.java
src/main/java/im/toduck/domain/concentration/presentation/dto/response/ConcentrationPercentResponse.java
src/main/java/im/toduck/domain/concentration/presentation/dto/response/ConcentrationResponse.java
src/main/java/im/toduck/global/config/web/WebConfig.java
src/main/java/im/toduck/global/config/web/converter/YearMonthConverter.java

> 특정 연월의 집중도 평균을 계산하여 반환하는 API를 추가했습니다.
> 집중 조회 시 날짜를 "yyyy-MM"으로 반환하도록 수정했습니다.
> yearMonth 파라미터 입력 시 타입을 String 말고 YearMonth(Converter)로 받도록 수정했습니다.
**1️⃣ 작업내용1**
- 설명1
<br/>

특정 연월의 집중 평균 조회 API와 수정사항

---

src/main/java/im/toduck/domain/routine/common/mapper/RoutineMapper.java
src/main/java/im/toduck/domain/social/presentation/api/SocialProfileApi.java
src/main/java/im/toduck/domain/social/presentation/dto/response/UserProfileRoutineListResponse.java

**1️⃣ [소셜 프로필 - 공개 루틴 조회] API 문서 수정**
**[수정전]**
```JAVA
@ApiResponseExplanations(
success = @ApiSuccessResponseExplanation(
responseClass = MyRoutineAvailableListResponse.class, <-------
description = "루틴 목록 조회 성공, 루틴의 고유 Id, 루틴 Color, 완료 여부를 반환합니다."
)
```
**[수정후]**
```JAVA
@ApiResponseExplanations(
success = @ApiSuccessResponseExplanation(
responseClass = UserProfileRoutineListResponse.class, <------
description = "루틴 목록 조회 성공, 루틴의 고유 Id, 루틴 Color, 완료 여부를 반환합니다."
)
```
<br/>
**2️⃣ [소셜 프로필 - 공개 루틴 조회] 응답시 카테고리 색상 필드 추가**
```JAVA
public record UserProfileRoutineResponse(
...
@Schema(description = "루틴 색상(null 이면 없는 색상)", example = "#FCDCDF")
String color,
...
) {
}
```
<br/>
- 궁금한 점 있으시면 댓글 남겨주세요!

소셜 프로필 - 공개 루틴 조회 api문서 수정

---

src/main/java/im/toduck/domain/mypage/domain/service/MyPageService.java
src/main/java/im/toduck/domain/mypage/domain/usecase/MyPageUseCase.java
src/main/java/im/toduck/domain/mypage/presentation/api/MyPageApi.java
src/main/java/im/toduck/domain/mypage/presentation/controller/MyPageController.java
src/main/java/im/toduck/domain/mypage/presentation/dto/request/ProfileImageUpdateRequest.java
src/main/java/im/toduck/domain/user/persistence/repository/querydsl/UserRepositoryCustom.java
src/main/java/im/toduck/domain/user/persistence/repository/querydsl/UserRepositoryCustomImpl.java
src/test/java/im/toduck/domain/mypage/domain/usecase/MyPageUseCaseTest.java

**1️⃣ 프로필 사진 변경**
- 프로필 사진 변경 api입니다. `CUD`를 해당 api로 한번에 쓸 수 있습니다.
> 다른 도메인의 S3 사진 수정과 삭제를 확인하였을 때, 사진을 삭제할 때 데이터베이스 상에서 url을 삭제하는 로직까지는 확인했지만, S3 자체의 사진을 삭제하는 로직은 찾지 못하였습니다. 데이터베이스 상에서만 삭제하고 S3에 올라간 사진은 따로 삭제해주지 않는 것인지, 혹은 제가 해당 로직을 발견하지 못한 것인지 궁금합니다!

프로필 사진 변경 API 개발

---

sql/init.sql
src/main/java/im/toduck/domain/schedule/common/mapper/ScheduleMapper.java
src/main/java/im/toduck/domain/schedule/presentation/dto/request/ScheduleCompleteRequest.java
src/main/java/im/toduck/domain/schedule/presentation/dto/response/ScheduleHeadResponse.java
src/main/resources/application-prod.yml

**1️⃣ 일정 Api 에서 역직렬화 에러 및 init.sql enum 누락 에러 해결**
- request dto 에서 LocalDate 역직렬화를 안해서 생기는 에러 해결
- init sql 에서 enum 누락에서 생기는 에러 해결
<br/>
**2️⃣ 일정 기간 조회 API 에 memo 필드 추가**
- memo 필드 추가해달라는 프론트 요청으로 추가했습니다
<br/>
**3️⃣ OIDC prod profile 환경 설정**
- prod 프로필에서 OIDC 설정이 누락되어 있어서 수정했습니다
<br/>

일정 및 oidc 에러 수정

---

sql/init.sql
src/main/java/im/toduck/domain/person/persistence/entity/PlanCategory.java
src/main/java/im/toduck/domain/routine/common/mapper/RoutineMapper.java
src/main/java/im/toduck/domain/routine/domain/service/RoutineRecordService.java
src/main/java/im/toduck/domain/routine/domain/service/RoutineService.java
src/main/java/im/toduck/domain/routine/domain/usecase/RoutineUseCase.java
src/main/java/im/toduck/domain/routine/persistence/entity/Routine.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRecordRepositoryCustom.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRecordRepositoryCustomImpl.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRepositoryCustomImpl.java
src/main/java/im/toduck/domain/routine/presentation/api/RoutineApi.java
src/main/java/im/toduck/domain/routine/presentation/controller/RoutineController.java
src/main/java/im/toduck/domain/routine/presentation/dto/request/RoutineCreateRequest.java
src/main/java/im/toduck/domain/routine/presentation/dto/request/RoutineUpdateRequest.java
src/main/java/im/toduck/domain/routine/presentation/dto/response/MyRoutineAvailableListResponse.java
src/main/java/im/toduck/domain/routine/presentation/dto/response/MyRoutineRecordReadListResponse.java
src/main/java/im/toduck/global/helper/DaysOfWeekBitmask.java
src/main/resources/application-local.yml
src/test/java/im/toduck/architecture/test/fixtures/FixturesRulesTest.java
src/test/java/im/toduck/builder/TestFixtureBuilder.java
src/test/java/im/toduck/domain/routine/domain/service/RoutineRecordServiceTest.java
src/test/java/im/toduck/domain/routine/domain/service/RoutineServiceTest.java
src/test/java/im/toduck/domain/routine/domain/usecase/RoutineUseCaseTest.java
src/test/java/im/toduck/domain/routine/persistence/repository/RoutineRecordRepositoryTest.java
src/test/java/im/toduck/domain/routine/persistence/repository/RoutineRepositoryTest.java
src/test/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCaseTest.java
src/test/java/im/toduck/domain/social/domain/usecase/SocialProfileUseCaseTest.java
src/test/java/im/toduck/fixtures/routine/RoutineFixtures.java
src/test/java/im/toduck/fixtures/routine/RoutineRecordFixtures.java
src/test/java/im/toduck/fixtures/routine/RoutineWithAuditInfo.java

루틴 수정 기능 구현 및 루틴 조회, 삭제 로직 재구성
**1️⃣ 루틴 수정 API 개발**
- 루틴의 제목, 카테고리, 색상, 시간, 공개 여부, 반복 요일, 알림 시간, 메모 수정 기능 구현
- 각 필드별 변경 여부 플래그를 통한 선택적 업데이트 지원
- 종일 루틴 ↔ 특정 시간 루틴 간 변경 지원, 반복 요일 변경 지원
- 반복 요일 패턴 변경 지원
- PUT /api/routines/{routineId} 엔드포인트 추가
**2️⃣ 루틴 스케줄 변경 히스토리 관리**
- `schedule_modified_at` 필드 추가로 루틴 일정 변경 시점 기록
- 루틴 시간 또는 반복 요일 변경 시 미래의 미완료 기록 자동 정리
- 루틴 수정/삭제 시 과거 기록은 유지하고 미래 기록만 관리하는 메커니즘
- `saveMissingIncompleteRecordsInBulk` 메서드 추가로 스케줄 변경 간 누락된 기록 보존
- **루틴 스케줄 변경 관리**
- 루틴 이행 이력을 정확하게 보존하면서 미래 기록은 새로운 설정에 맞게 생성됩니다. 예를 들어, 사용자가 월/수/금 루틴을 화/목 루틴으로 변경하더라도 변경 이전의 월/수/금 날짜들에 대한 기록은 그대로 유지됩니다.
- 루틴의 시간이나 반복 요일이 변경될 경우:
1. 변경 시점(`LocalDateTime.now()`)을 기준으로 미래의 미완료 루틴 기록을 삭제
2. 이전 스케줄 변경 시점부터 현재 시점까지의 누락된 기록을 생성하여 과거 기록 보존
3. Routine 엔티티의 `scheduleModifiedAt` 필드를 현재 시점으로 업데이트
**3️⃣ 루틴 조회 …

루틴 수정 기능 개발

---

src/main/java/im/toduck/domain/routine/presentation/dto/request/RoutineCreateRequest.java
src/main/java/im/toduck/domain/routine/presentation/dto/request/RoutineUpdateRequest.java

잘 못 지정된 카테고리 Validate를 NotBlank에서 NotNull로 수정
(String이 아닌 필드에 NotBlank  적용으로 발생한 문제)

카테고리 Validate를 NotBlank에서 NotNull로 수정

---

src/main/java/im/toduck/domain/routine/common/mapper/RoutineMapper.java
src/main/java/im/toduck/domain/social/presentation/dto/response/UserProfileRoutineListResponse.java

**1️⃣ 소셜 프로필 - 공개 루틴 목록 조회 시  반복 날짜 응답 추가**
```JAVA
public record UserProfileRoutineListResponse(
List<UserProfileRoutineResponse> routines
) {
public record UserProfileRoutineResponse(
...
@JsonSerialize(using = DayOfWeekListSerializer.class)
@Schema(description = "반복 요일", example = "[\"MONDAY\",\"TUESDAY\"]")
List<DayOfWeek> daysOfWeek,
...
) {
}
}
```
<br/>
**2️⃣ 루틴 Detail - memo 값 응답**
``` JAVA
public static RoutineDetailResponse toRoutineDetailResponse(final Routine routine) {
...
return RoutineDetailResponse.builder()
...
.memo(routine.getMemoValue())       <----- Mapper에서 응답 하지 않던 것 수정
...
}
```
<br/>

소셜 관련 응답 필드 추가 및 수정

---

src/main/java/im/toduck/domain/routine/domain/service/RoutineService.java
src/main/java/im/toduck/domain/routine/domain/usecase/RoutineUseCase.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRepositoryCustomImpl.java
src/test/java/im/toduck/domain/routine/domain/service/RoutineServiceTest.java

**1️⃣ 루틴 생성 및 수정 시 당일 기록이 누락되는 문제 해결**
- RoutineService에서 불필요한 필터링 로직을 제거하여 당일 생성/수정된 루틴도 정상적으로 조회되도록 수정
- 루틴 시간과 스케줄 수정 시간을 비교하는 복잡한 로직을 제거하여 시간대 문제 해결
<br/>
**2️⃣ saveMissingIncompleteRecordsInBulk 메서드 간소화**
- 복잡한 시간 비교 로직 제거 및 코드 간소화
- 불필요한 날짜 필터링 로직 제거
<br/>
**3️⃣ 미사용 코드 및 불필요한 임포트 제거**
- LocalTime 및 ArrayList 등 불필요한 임포트 제거
- 미사용 메서드 routineCreatedOnOrBeforeDate 제거

루틴 생성 및 수정 시 당일 기록이 누락되는 문제 해결

---

src/main/java/im/toduck/domain/routine/domain/service/RoutineRecordService.java
src/main/java/im/toduck/domain/routine/domain/usecase/RoutineUseCase.java
src/main/java/im/toduck/domain/routine/persistence/entity/Routine.java
src/main/java/im/toduck/domain/routine/persistence/entity/RoutineRecord.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRecordRepositoryCustomImpl.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRepositoryCustomImpl.java
src/main/java/im/toduck/domain/routine/presentation/api/RoutineApi.java
src/main/java/im/toduck/domain/routine/presentation/controller/RoutineController.java

**1️⃣ 개별 루틴 삭제 기능 구현**
- 특정 날짜의 개별 루틴만 삭제할 수 있는 기능 구현
- 실제 삭제가 아닌 soft delete 방식 적용 (deletedAt 필드 사용)
<br/>
**2️⃣ 기존 루틴 조회 기능 개선**
- 삭제된 루틴을 포함/제외하는 기능 구분 구현
- getRecords → getRecordsIncludingDeleted 메서드명 변경
- 루틴 조회 시 삭제되지 않은 루틴만 반환하도록 필터링 로직 추가
<br/>
**3️⃣ API 엔드포인트 추가**
- 개별 루틴 삭제를 위한 DELETE `/routines/{routineId}/individual?date=YYYY-MM-DD` 엔드포인트 구현
- 삭제 요청 시 이미 기록이 있으면 삭제 상태로 변경, 없으면 삭제 상태로 생성하는 로직 구현 (동시성 문제 해결 필요)

개별 루틴 삭제 기능 구현

---

src/main/java/im/toduck/domain/routine/common/dto/DailyRoutineData.java
src/main/java/im/toduck/domain/routine/common/mapper/RoutineMapper.java
src/main/java/im/toduck/domain/routine/domain/service/RoutineRecordService.java
src/main/java/im/toduck/domain/routine/domain/service/RoutineService.java
src/main/java/im/toduck/domain/routine/domain/usecase/RoutineUseCase.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRecordRepositoryCustom.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRecordRepositoryCustomImpl.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRepositoryCustom.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRepositoryCustomImpl.java
src/main/java/im/toduck/domain/routine/presentation/api/RoutineApi.java
src/main/java/im/toduck/domain/routine/presentation/controller/RoutineController.java
src/main/java/im/toduck/domain/routine/presentation/dto/response/MyRoutineRecordReadMultipleDatesResponse.java
src/main/java/im/toduck/global/exception/ExceptionCode.java
src/main/java/im/toduck/global/helper/DaysOfWeekBitmask.java
src/test/java/im/toduck/architecture/main/domain/LayeredArchitectureTest.java
src/test/java/im/toduck/domain/routine/domain/usecase/RoutineUseCaseTest.java
src/test/java/im/toduck/domain/routine/persistence/repository/RoutineRecordRepositoryTest.java
src/test/java/im/toduck/domain/routine/persistence/repository/RoutineRepositoryTest.java

**1️⃣ 여러 날짜에 대한 루틴 기록 조회 API 추가**
- `/routines/me/dates?startDate=2024-12-02&endDate=2024-12-08` 엔드포인트 추가
- 단일 날짜가 아닌 기간으로 루틴과 루틴 기록을 조회할 수 있는 기능 구현
- 최대 조회 기간을 13일(`MAX_ROUTINE_DATE_RANGE_DAYS`)로 제한하여 성능과 리소스 사용량 최적화
- 시작일과 종료일이 유효한지 검증하는 로직 추가 (`ExceptionCode.EXCEED_ROUTINE_DATE_RANGE`)
<br/>
**2️⃣ 날짜별 루틴 데이터 추상화를 위한 DailyRoutineData 추가**
- 특정 날짜의 모든 루틴 데이터를 담는 레코드 클래스 구현
- 날짜(`date`), 미완료 루틴 목록(`routines`), 루틴 기록 목록(`routineRecords`)을 캡슐화하여 코드 가독성 향상
- 기존 단일 날짜 조회 로직(`readMyRoutineRecordList`)도 DailyRoutineData를 활용하도록 리팩토링하여 코드 일관성 확보
- 서비스와 프레젠테이션 계층 간 데이터 전달 구조 개선
<br/>
**3️⃣ 루틴 조회 로직 최적화**
- 날짜 범위 기반 쿼리 성능 최적화 
- 특정 기간의 루틴을 한 번에 조회하는 메소드 추가 (`findRoutinesByDateBetween`)
- 날짜 범위에 맞는 요일 비트마스크 필터링을 통한 쿼리 효율성 향상 (`routineMatchesDateRange`)
- 요일 비트마스크 유틸리티에 날짜 범위 기능 확장 …

여러 날짜에 대한 루틴 기록 조회 기능 추가

---

src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRepositoryCustomImpl.java
src/test/java/im/toduck/domain/routine/domain/usecase/RoutineUseCaseTest.java
src/test/java/im/toduck/fixtures/routine/RoutineFixtures.java

클라이언트측에서 루틴 범위 조회 시 루틴이 다음 주부터 보인다는 오류 제보를 받았습니다.
범위 조회가 아닌 단건 조회에서는 정상적으로 동작하는 것을 확인했고, 문제 재현을 위해 테스트 코드를 작성했습니다.
범위 조회 시 `scheduleModifiedOnOrBeforeDate` 조건이 startDate로 설정되어 있어 일부 루틴이 정상적으로 조회되지 않는 현상을 확인하고 수정했습니다.
| 루틴 상세 | 루틴이 보이지 않음 |
|---------|---------|
| ![루틴이 보이지 않음](https://github.com/user-attachments/assets/fab26e91-b664-4298-b221-0326e278155a) | ![루틴 상세 정보](https://github.com/user-attachments/assets/ff10992f-5f3a-4db2-917d-6f3e43d27ea2) |
**1️⃣ 루틴 범위 조회 기능 오류 수정**
- `RoutineRepositoryCustomImpl` 클래스의 `findAllByUserAndDateRange` 메서드에서 `scheduleModifiedOnOrBeforeDate` 조건을 startDate에서 endDate로 변경
- 이 변경으로 지정된 날짜 범위 내의 루틴을 모두 올바르게 조회할 수 있게 됨
<br/>
**2️⃣ 테스트 케이스 추가**
- 다중 날짜 조회 결과가 각 날짜별 단일 조회 결과와 동일한지 검증하는 테스트 케이스를 하나 더 추가

특정 케이스에서 범위 조회가 제대로 동작하지 않는 문제 해결

---

src/main/java/im/toduck/domain/mypage/common/mapper/MyPageMapper.java
src/main/java/im/toduck/domain/mypage/domain/service/MyPageService.java
src/main/java/im/toduck/domain/mypage/domain/usecase/MyPageUseCase.java
src/main/java/im/toduck/domain/mypage/presentation/api/MyPageApi.java
src/main/java/im/toduck/domain/mypage/presentation/controller/MyPageController.java
src/main/java/im/toduck/domain/mypage/presentation/dto/response/BlockedUsersResponse.java
src/main/java/im/toduck/domain/user/persistence/repository/querydsl/UserRepositoryCustom.java
src/main/java/im/toduck/domain/user/persistence/repository/querydsl/UserRepositoryCustomImpl.java
src/test/java/im/toduck/builder/TestFixtureBuilder.java
src/test/java/im/toduck/domain/mypage/domain/usecase/MyPageUseCaseTest.java

**1️⃣ 마이페이지 - 차단한 유저 조회 API 개발**
- 차단 했지만 탈퇴한 회원은 조회시 제외
- 궁금한 점 있으면 댓글 남겨주세요!

마이페이지 - 차단한 유저 조회 API 개발

---

sql/init.sql
src/main/java/im/toduck/domain/concentration/domain/service/ConcentrationService.java
src/main/java/im/toduck/domain/concentration/persistence/repository/ConcentrationRepository.java
src/main/java/im/toduck/domain/diary/domain/service/DiaryService.java
src/main/java/im/toduck/domain/diary/persistence/repository/DiaryRepository.java
src/main/java/im/toduck/domain/mypage/common/mapper/AccountDeletionLogMapper.java
src/main/java/im/toduck/domain/mypage/domain/service/MyPageService.java
src/main/java/im/toduck/domain/mypage/domain/usecase/MyPageUseCase.java
src/main/java/im/toduck/domain/mypage/persistence/entity/AccountDeletionLog.java
src/main/java/im/toduck/domain/mypage/persistence/entity/AccountDeletionReason.java
src/main/java/im/toduck/domain/mypage/persistence/repository/AccountDeletionLogRepository.java
src/main/java/im/toduck/domain/mypage/presentation/api/MyPageApi.java
src/main/java/im/toduck/domain/mypage/presentation/controller/MyPageController.java
src/main/java/im/toduck/domain/mypage/presentation/dto/request/UserDeleteRequest.java
src/main/java/im/toduck/domain/routine/domain/service/RoutineService.java
src/main/java/im/toduck/domain/routine/persistence/repository/RoutineRepository.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRepositoryCustom.java
src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRepositoryCustomImpl.java
src/main/java/im/toduck/domain/social/domain/service/SocialBoardService.java
src/main/java/im/toduck/domain/social/persistence/repository/SocialRepository.java
src/main/java/im/toduck/domain/user/domain/service/FollowService.java
src/main/java/im/toduck/domain/user/domain/service/UserService.java
src/main/java/im/toduck/domain/user/persistence/repository/BlockRepository.java
src/main/java/im/toduck/domain/user/persistence/repository/FollowRepository.java
src/main/java/im/toduck/domain/user/persistence/repository/querydsl/UserRepositoryCustom.java
src/main/java/im/toduck/domain/user/persistence/repository/querydsl/UserRepositoryCustomImpl.java
src/test/java/im/toduck/domain/mypage/domain/usecase/MyPageUseCaseTest.java

**1️⃣ 회원 탈퇴 사유 저장**
- 회원 탈퇴 사유에 대해 추후 활용 가능성이 높지 않을까 생각하여, 데이터베이스 상에서도 남길 수 있도록 하였습니다.
- 테이블의 생성 SQL문은 다음과 같습니다.
```MySQL
CREATE TABLE account_deletion_log
(
id          BIGINT PRIMARY KEY auto_increment,
user_id     BIGINT                                                                                      NOT NULL,
reason_code ENUM ('HARD_TO_USE', 'NO_FEATURES', 'MANY_ERRORS', 'BETTER_APP', 'SWITCH_ACCOUNT', 'OTHER') NOT NULL,
reason_text VARCHAR(130)                                                                                NOT NULL,
created_at  DATETIME                                                                                    NOT NULL,
FOREIGN KEY (user_id) REFERENCES users (id)
);
```
<br/>
**2️⃣ 회원 연관 데이터 삭제**
- `Follow`와 `Block`의 경우 `hard delete`, 나머지 경우는 `soft …

회원 탈퇴 API 개발

---

src/main/java/im/toduck/domain/routine/domain/usecase/RoutineUseCase.java
src/main/java/im/toduck/global/lock/DistributedLock.java
src/main/java/im/toduck/global/lock/LockAcquisitionException.java
src/main/java/im/toduck/global/lock/RedisLockManager.java
src/main/java/im/toduck/global/lock/TransactionExecutor.java
src/test/java/im/toduck/architecture/main/domain/domain/UseCaseRulesTest.java
src/test/java/im/toduck/domain/routine/domain/usecase/RoutineUseCaseConcurrencyTest.java
src/test/java/im/toduck/domain/routine/domain/usecase/RoutineUseCaseTest.java
src/test/java/im/toduck/global/lock/DistributedLockTest.java
src/test/java/im/toduck/global/lock/RedisLockManagerTest.java

- 한 명의 사용자가 루틴 완료 상태를 변경할 때(또는 개별 삭제할 때) "없으면 생성, 있으면 수정" 방식으로 동작
- Upsert 패턴으로 인해 동일 루틴, 동일 날짜에 대해 중복 기록이 저장되는 문제 확인
- 현재 동시성 테스트를 통해 해당 문제가 재현됨
- 클라이언트 측 디바운싱: 필수적이지만 완전한 해결책은 아님 (다중 클라이언트 접속 가능성, 네트워크 지연 등)
- 복합 유니크 제약조건: 예외 처리 복잡성, 벌크 연산 시 성능 저하 우려
- MySQL Upsert: JPA 표준이 아니며 벤더 종속성 발생(또한 기존 비즈니스 로직 가독성 해칠 우려, 유니크 제약 조건 필요)
- 낙관적/비관적 락: 레코드가 없을 때 생성하는 로직에는 적용 불가(비관적 락의 경우 테이블 락 우려)
- 분산 락 (선택): 기존 로직 수정 최소화, Redis 인프라 활용, 구현 비교적 간단
**1️⃣ 분산 락 시스템 구현**
- Redis 기반의 분산 락 시스템 구현 (`DistributedLock`, `RedisLockManager`, `LockAcquisitionException`)
- 락 획득 실패 시 재시도 메커니즘 포함 (최대 재시도 횟수, 재시도 대기 시간 설정 가능)
- 락 획득 실패 시 지수 백오프 및 지터 적용으로 효율적인 재시도 구현
- TransactionExecutor를 활용한 독립적 트랜잭션 컨텍스트 제공
- Lua 스크립트를 활용한 안전한 락 해제 구현 (락 소유자만 해제 가능)
**2️⃣ 루틴 완료 상태 변경 동시성 처리**
- `updateRoutineCompletion` 메서드에 분산 락 …

 루틴 동시성 문제 해결

---

src/main/java/im/toduck/domain/user/persistence/repository/querydsl/UserRepositoryCustomImpl.java

- 회원 탈퇴 후에 로그인 및 api 사용이 가능한 현상 발생
**1️⃣ 회원 탈퇴 시 로그인 관련 정보 모두 삭제**
- 회원 탈퇴 시 로그인과 관련한 정보를 모두 삭제하였습니다.
- 기존: `닉네임`, `프로필 사진` 만 삭제 -> 변경 후: `휴대폰 번호`, `로그인 ID`, `비밀번호`, `이메일`을 추가로 삭제

회원 탈퇴 후 로그인이 가능한 현상 해결
